[[redirects]]
  from = "/api/check-repository"
  to = "/.netlify/functions/check-repository"
  status = 200

[[redirects]]
  from = "/api/oauth/redirect"
  to = "/.netlify/functions/authenticate-user"
  status = 200

[build]
  functions = "functions"


[[plugins]]
  package = "@netlify/plugin-functions-install-core"